# NB: Any variables set here will be accessible via site.variable_name in other pages using Liquid syntax

name: Modelling minerals for nuclear waste storage
title: Modelling minerals for nuclear waste storage
description: James Prime, PhD-in-Progress
#google_analytics:
show_downloads: false # Was true originally (changed 09/07/2017)
theme: jekyll-theme-leap-day
# markdown: rdiscount # Supposed to be the closest to GFM
markdown: kramdown

gems:
  - jekyll-mentions

# Adds /blog/ in between homepage URL and year/month/day/title.html
permalink: /blog/:year/:month/:day/:title

# Handling reading
include: [".htaccess", "_pages"]

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
